version: '3.8'

services:
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      # Port AMQP
      - "5672:5672"
      # Port web interface
      - "15672:15672"
    restart: always

  # Log Ingestor
  log_ingestor:
    build: ./services/log_ingestor
    container_name: log_ingestor
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    restart: always

  # ElasticSearch Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always

  # Kibana service
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    restart: always

  # Log Processor
  log_processor:
    build: ./services/log_processor
    container_name: log_processor
    depends_on:
      - rabbitmq
      - elasticsearch
    restart: always

  # Ingestion script
  ingestion_script:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    profiles: ["setup"]
    depends_on:
      - log_ingestor

volumes:
  es_data: